<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>
      $(Description)

      Microsoft.Extensions.DependencyInjection integration: configures AutoFactories to generate
      factories that resolve [FromFactory] parameters from an IServiceProvider, and adds extension
      methods to register the generated factories and their interfaces with the built-in
      Microsoft dependency injection container.
    </Description>
    <PackageIcon>Icon.jpg</PackageIcon>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
  </PropertyGroup>
  <ItemGroup>
    <None Include="..\..\img\Icon.jpg">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\AutoFactories\AutoFactories.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Update="Icon.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Update="GitVersion.MsBuild">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
</Project>